name: Deploy to test pypi

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag to use in deployment'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: test

      - name: Build the package
        env:
          PYPI_TAG: ${{ github.event.inputs.tag }}
        run: |
          python -m pip install --upgrade build
          python -m build -w

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/

